name: Build LaTeX Document

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Resume.tex  # Replace with your main .tex file

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: Resume.pdf  # Replace with the name of your generated PDF
