name: Build and Deploy LaTeX Document

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Resume.tex  # Ensure this matches your main .tex file

    - name: Move PDF to Root Directory
      run: |
        cp Resume.pdf ./  # Copy Resume.pdf to the root directory for deployment

    - name: Create index.html
      run: |
        echo "<html><body><h1>Welcome to the Utils Repository</h1><p>Download the generated PDF: <a href='Resume.pdf'>Resume.pdf</a></p></body></html>" > index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Deploy from the root directory
        keep_files: false  # This ensures a fresh deployment, clearing out old files
